name = "sentmail-api"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Custom domain for production
# This will be configured in Cloudflare dashboard for sentmail.glitchidea.com
routes = [
  { pattern = "sentmail.glitchidea.com/*", custom_domain = true }
]

# Environment variables (will be set in Cloudflare dashboard)
# These are placeholder names - actual values set in dashboard
[env.production.vars]
# SMTP_HOST = "your-smtp-server.com"
# SMTP_PORT = "587" 
# SMTP_USER = "your-smtp-username"
# SMTP_PASS = "your-smtp-password"
# SMTP_SECURE = "false"
# RECEIVER_EMAIL = "info@glitchidea.com"
# DEBUG = "false"

# Development environment
[env.development.vars]
# Same variables for development testing

# Node.js compatibility for nodemailer
[build]
command = ""

# Enable nodejs compatibility for email functionality
[[module.rules]]
type = "ESModule"
globs = ["**/*.js"]

# Worker settings
[workers]
format = "modules"
