name: GitHub Pages Deploy and Email Handler

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ send_email ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  send_email:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: Yeni İletişim Formu Mesajı
          from: ${{ secrets.GMAIL_USER }}
          to: info@glitchidea.com
          body: |
            Yeni bir iletişim formu mesajı aldınız:
            
            Gönderen: ${{ github.event.client_payload.name }}
            E-posta: ${{ github.event.client_payload.email }}
            
            Mesaj:
            ${{ github.event.client_payload.message }}